#!/bin/sh
currDate=$(date)
echo "GUIDING DEVICE PLUGGED" $currDate>> /home/pi/Software/MyApplications/IndiGuider02/guiderdevruleoutput.txt
export DISPLAY=:10.0
export XAUTHORITY=/home/pi/.Xauthority
notify-send Guiding Guiding -t 3000
